M48
; DRILL file {KiCad 7.0.1-0} date 2023 October 24, Tuesday 00:05:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-24T00:05:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0827
%
G90
G05
T1
X4.4213Y-1.3524
X4.4213Y-1.5492
T2
X4.565Y-1.9311
X4.565Y-2.0492
T3
X3.19Y-1.42
X3.19Y-1.89
T0
M30
